### PR TITLE
Update VayneHunterReborn.cs

### PR DESCRIPTION
**Pull request by finndev**

### CODE REVIEW

**Comment by ChewyMoon** [comment]
:+1:

**Comment by DZ191** [comment]
Much pull very request

**Comment by nabbhacker** [comment]
ROFL

**Comment by Hellsing** [comment]
Wut?

**Comment by HoesLeaguesharp** [comment]
what is going on

**Comment by DZ191** [comment]
Just Asuna being salty cause it's 40 °C outside

**Comment by LunarBlue** [comment]
XD

**Comment by nabbhacker** [comment]
Saltier than the sea itself.

**Comment by HoesLeaguesharp** [comment]
hellsing is here

**Comment by ScienceARK** [comment]
ayylmao

**Comment by DZ191** [comment]
Still waiting :clock1:

**Comment by tr33s** [comment]
rawr

**Comment by legacy3** [comment]
Hellsing is alive :monkey_face:

**Comment by Onfinite** [comment]
Hello guys :)

**Comment by HoesLeaguesharp** [comment]
shoutbox v2

**Comment by Hellsing** [comment]
Sup

**Comment by legacy3** [comment]
better than twitch chat :kappa:

**Comment by DZ191** [comment]
well this is unexpected. Hi Birdie!

**Comment by finndev** [comment]
guys why l# crack bugsplat for me???

**Comment by jQueryBase64MyAss** [comment]
:o2:

**Comment by Hellsing** [comment]
hi i am twilight lol from BoL#

**Comment by legacy3** [comment]
fix your crack, lost a ranked due to it

**Comment by tr33s** [comment]
@finndev use borderless kappa

**Comment by LunarBlue** [comment]
finn you need fix your registry

**Comment by Onfinite** [comment]
https://www.youtube.com/watch?v=5UM3ecX69Jo

Hey Dan what's up

**Comment by HoesLeaguesharp** [comment]
finndev, i guess 6 months wasn't enough Kappa

**Comment by Downvote** [comment]
BUGSPLAT PLS HELB HOW FYX????????????????

**Comment by stefsot** [comment]
party time

**Comment by DZ191** [comment]
I'm salty cause it's 40 *C and conditioner is not working ;(

**Comment by ChewyMoon** [comment]
when cn anti closure

**Comment by LunarBlue** [comment]
Chevy is here xd

**Comment by HoesLeaguesharp** [comment]
ANTI TP WHEM

**Comment by Onfinite** [comment]
hey guys now that the old team is here let's start a new program EloSharp LolHT Turbo 2.0

**Comment by legacy3** [comment]
hellsing update brand please

**Comment by ehmehe** [comment]
hellsing update brand please

**Comment by jQueryBase64MyAss** [comment]
fuck you @ehmehe

**Comment by Downvote** [comment]
hellsing update brand please

**Comment by Hellsing** [comment]
@ehmehe http://puu.sh/j2yLj/b4642d6105.png

**Comment by h3h3** [comment]
hellsing update brand please

**Comment by LunarBlue** [comment]
xd

**Comment by legacy3** [comment]
twitch should steal this chat system, it works far better lol

**Comment by ChewyMoon** [comment]
@h3h3 update leaguesharp live

**Comment by ehmehe** [comment]
@Hellsing Kalista too please Kappa

**Comment by DZ191** [comment]
I'm about to hard reset, bye guys ;(

**Comment by ChewyMoon** [comment]
Nooooooo!

**Comment by ehmehe** [comment]
RIP

**Comment by Onfinite** [comment]
rip asuna

**Comment by LunarBlue** [comment]
CN soon ?

**Comment by Downvote** [comment]
R I P

**Comment by HoesLeaguesharp** [comment]
party over?

**Comment by legacy3** [comment]
downvote pls, cry more at jodus

**Comment by ChewyMoon** [comment]
Nope

**Comment by Hellsing** [comment]
Cloudrop soon(tm)

**Comment by ChewyMoon** [comment]
ayy lmao

**Comment by HoesLeaguesharp** [comment]
LOL Downvote, you got busted

**Comment by ChewyMoon** [comment]
asuna u have to delete this pr lmao u noob

**Comment by Onfinite** [comment]
XD

**Comment by y1n** [comment]
dasds

**Comment by ehmehe** [comment]
wow that's like old times here :]

**Comment by legacy3** [comment]
noob

**Comment by HoesLeaguesharp** [comment]
I CAN STILL TALK

**Comment by ehmehe** [comment]
lol

**Comment by ChewyMoon** [comment]
same

**Comment by Downvote** [comment]
there was a bik kappa in the text mr legacy

**Comment by ehmehe** [comment]
wow that's like old times here :]

**Comment by HoesLeaguesharp** [comment]
Asuna you dun goofd

**Comment by ChewyMoon** [comment]
imeh update my assemblies

**Comment by Onfinite** [comment]
Ehrenmänner 3.0 ?

**Comment by ehmehe** [comment]
#FreeHellsing

**Comment by Hellsing** [comment]
Not like I was banned on L$ :P

**Comment by LunarBlue** [comment]
xd what is LS account

**Comment by HoesLeaguesharp** [comment]
@Hellsing where are you now

**Comment by ChewyMoon** [comment]
@HoesLeaguesharp he ded nigga

**Comment by HoesLeaguesharp** [comment]
@ChewyMoon is that a ghost then?

**Comment by ChewyMoon** [comment]
ye

**Comment by Hellsing** [comment]
@CrunchyMars pls

**Comment by DZ191** [comment]
:^D

**Comment by ehmehe** [comment]
The real question is: Does @LunarBlue knows what a struct is?

**Comment by h3h3** [comment]
cn updated?

**Comment by ehmehe** [comment]
@h3h3 :]

**Comment by ChewyMoon** [comment]
@h3h3 no, update pls we wait for bigman for anti closure

**Comment by LunarBlue** [comment]
h3h3 fix pls

**Comment by DZ191** [comment]
HDF OR HDL

**Comment by h3h3** [comment]
@ChewyMoon anti sailing?

**Comment by LunarBlue** [comment]
HDL

**Comment by ChewyMoon** [comment]
@h3h3 update clothes pls

**Comment by h3h3** [comment]
http://www.kik.de/

**Comment by DZ191** [comment]
downloadmoreram.com

**Comment by h3h3** [comment]
nice link

**Comment by Hellsing** [comment]
Thanks

**Comment by HoesLeaguesharp** [comment]
WELL you big boys have your convo, bye

**Comment by LunarBlue** [comment]
http://www.npd.kz

**Comment by DZ191** [comment]
cya hoes

**Comment by ehmehe** [comment]
@Hellsing Update Kalista :(

**Comment by ChewyMoon** [comment]
@ehmehe yea i did, honda c+p

**Comment by stefsot** [comment]
Hellsing is in a better place.

**Comment by Aviv258958** [comment]
nice memes

**Comment by DZ191** [comment]
ebig memes

**Comment by ehmehe** [comment]
buddy memes

**Comment by Aviv258958** [comment]
very bik

**Comment by DZ191** [comment]
:clock1: for blacky to get in here so you guys have your old german chat

**Comment by blackyy** [comment]
oh hi guys i just woke up

**Comment by Aviv258958** [comment]
LOL. ༼ ºل͜º ༽ºل͜º ༽ºل͜º ༽ ＥＶＥＲＹＯＮＥ，ＧＥＴ ＩＮ ＨＥＲＥ ༼ ºل͜º༼ ºل͜º༼ ºل͜º ༽

**Comment by ChewyMoon** [comment]
@LunarBlue come on ts bby

**Comment by legacy3** [comment]
finn pay hellsing pls

**Comment by ehmehe** [comment]
wow that's like Ehrenmänner sponsored by Github + some random idiots

**Comment by ehmehe** [comment]
#Hellsing #NeverForget

**Comment by Aviv258958** [comment]
nice references xddd

**Comment by blackyy** [comment]
nice memes my friend

**Comment by Onfinite** [comment]
hey blacky wie geht's lange nich gesehn

**Comment by DZ191** [comment]
I understood that, call me german god

**Comment by ChewyMoon** [comment]
shut up italian

**Comment by blackyy** [comment]
Ja echt lange nicht gesehen, geht einigermaßen, könnte besser sein :s

**Comment by DZ191** [comment]
it's 'shut up pizza' you fat american.

**Comment by ehmehe** [comment]
Please don't insult each other here. LeagueSharps Global Forum Rules also apply on Github Kappa

**Comment by Aviv258958** [comment]
holy mother of god. github chat should have mods now Kappa

**Comment by DZ191** [comment]
Ayy lmao

**Comment by Onfinite** [comment]
ich komm mal wieder in Skype on dann reden wir bisschen blacky :)

ich glaub die andren mögen mich nich mehr :/

**Comment by Aviv258958** [comment]
░░░░░░░░▄▀░░░░░░░░░░░░░▒▒▒▒▒▄░░░░░░░░░   
░░░░░░▄▀▒▒▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒█░░░░░░░░
░░░░░█▒▒▒▒░░░░▒▒▒▒▒▒▒▒▒▒░░░░▒▒█░░░░░░░
░░░░█▒▒▄▀▀▀▀▀▄▄▒▒▒▒▒▒▒▒▒▄▄▀▀▀▀▀▀▄░░░░░ 
░░▄▀▒▒▒▄█████▄▒█▒▒▒▒▒▒▒█▒▄█████▄▒█░░░░ 
░█▒▒▒▒▐██▄████▌▒█▒▒▒▒▒█▒▐██▄████▌▒█░░░ 
▀▒▒▒▒▒▒▀█████▀▒▒█▒░▄▒▄█▒▒▀█████▀▒▒▒█░░ 
▒▒▐▒▒▒░░░░▒▒▒▒▒█▒░▒▒▀▒▒█▒▒▒▒░░░░▒▒▒▒█░ 
▒▌▒▒▒░░░▒▒▒▒▒▄▀▒░▒▄█▄█▄▒▀▄▒▒▒░░░░▒▒▒▒▌ 
▒▌▒▒▒▒░▒▒▒▒▒▒▀▄▒▒█▌▌▌▌▌█▄▀▒▒▒▒▒░░░▒▒▒▐ 
▒▐▒▒▒▒▒▒▒▒▒▒▒▒▒▌▒▒▀███▀▒▌▒▒▒▒▒▒▒▒▒▒▒▒▌ 
▀▀▄▒▒▒▒▒▒▒▒▒▒▒▌▒▒▒▒▒▒▒▒▒▐▒▒▒▒▒▒▒▒▒▒▒█░ 
▀▄▒▀▄▒▒▒▒▒▒▒▒▐▒▒▒▒▒▒▒▒▒▄▄▄▄▒▒▒▒▒▒▄▄▀░░ 
▒▒▀▄▒▀▄▀▀▀▄▀▀▀▀▄▄▄▄▄▄▄▀░░░░▀▀▀▀▀▀░░░░░ 
▒▒▒▒▀▄▐▒▒▒▒▒▒▒▒▒▒▒▒▒▐░░░░░░░░░░░░░░░░░

**Comment by Onfinite** [comment]
dabei will ich wissen wie es imehs kadse geht :(

**Comment by ehmehe** [comment]
Please Konoe - Vergangenheit ist Vergangenehit :]

**Comment by ehmehe** [comment]
Sogar Apollo war ts

**Comment by DZ191** [comment]
I still wub you Konoe

**Comment by ehmehe** [comment]
Fehlt nur noch Hellsing :[

**Comment by Aviv258958** [comment]
wtf.. konoe is in github's chat but offline in skype all the time, nice memes Konoe chan

**Comment by blackyy** [comment]
Idd vergangenheit ist vergangenheit wie imeh sagt :] Man kann ja normal mit einander reden + iMehs Kadse geht es prima

**Comment by DZ191** [comment]
who the fuck is aviv lol

**Comment by Aviv258958** [comment]
ghost :s

**Comment by DZ191** [comment]
ghost who

**Comment by Aviv258958** [comment]
i'm Konoe's gf :X

**Comment by HoesLeaguesharp** [comment]
lol no

**Comment by h3h3** [comment]
bf?

**Comment by DZ191** [comment]
I'm a cat

**Comment by Aviv258958** [comment]
huehuehue brazil?

**Comment by blackyy** [comment]
no you're a pizza

**Comment by DZ191** [comment]
shut up loli

**Comment by blackyy** [comment]
best loli euw

**Comment by DZ191** [comment]
I was going to do some productive stuff today, then this PR happened 8D

**Comment by Hellsing** [comment]
@ehmehe Pls, ich bin TS

**Comment by Onfinite** [comment]
no time for TS :/

**Comment by LunarBlue** [comment]
blackfeeder 2.0 soon ? chevy later ill go now

**Comment by blackyy** [comment]
BlackFeeder 2.0 bik with SDK release Keepo

**Comment by LunarBlue** [comment]
xd

**Comment by ChewyMoon** [comment]
im waiting apollo

**Comment by DZ191** [comment]
Reunion :8ball:

**Comment by vperpl** [comment]
Kappa nulled.io sb hugs u all

**Comment by iJavai** [comment]
the fuck...

**Comment by myo** [comment]
where is elobuddy crack pls? i found it everywhere and it's not here

**Comment by ehmehe** [comment]
Hey guys, sup?

**Comment by LunarBlue** [comment]
hi imuh

**Comment by Aviv258958** [comment]
hello ( ͡°( ͡° ͜ʖ( ͡° ͜ʖ ͡°)ʖ ͡°) ͡°)

**Comment by ehmehe** [comment]
wow there are actually people who really read their mails

**Comment by LunarBlue** [comment]
yo immer xd

**Comment by Aviv258958** [comment]
wat? I'll let you kno I have very important mails ༼ つ  ͡° ͜ʖ ͡° ༽つ

**Comment by ChewyMoon** [comment]
imeh pls, you get a little blue dot in your notification bar in the top instantly

**Comment by ehmehe** [comment]
Hi

**Comment by DZ191** [comment]
Hi

**Comment by Aviv258958** [comment]
heyguys

**Comment by vperpl** [comment]
L# Crack is better it doesnt bugsplats on fullscreen.

**Comment by DZ191** [comment]
Who the fuck are all these randoms..

**Comment by nabbhacker** [comment]
rly

**Comment by tr33s** [comment]
xx

**Comment by blackyy** [comment]
stfu

**Comment by DZ191** [comment]
ayy

**Comment by Hellsing** [comment]
ayy lmao

**Comment by LunarBlue** [comment]
topkek

**Comment by iJavai** [comment]
hi, I'm new here

**Comment by ChewyMoon** [comment]
shut up corey

**Comment by DZ191** [comment]
Hi new here I'm DZ

**Comment by ChewyMoon** [comment]
nice meme

**Comment by ehmehe** [comment]
fluxy ist ein hurensohn XD

**Comment by Hellsing** [comment]
Warum?

**Comment by LunarBlue** [comment]
hab euch lieb keepo

**Comment by ChewyMoon** [comment]
rip fluxy

**Comment by ehmehe** [comment]
HALLO HELLSING

**Comment by Hellsing** [comment]
Sup

**Comment by ChewyMoon** [comment]
imeh decided to drink to keep the pain from fluxy leaving away

**Comment by blackyy** [comment]
Fluxy gone (party)

**Comment by ChewyMoon** [comment]
^

**Comment by DZ191** [comment]
Sayonara Fluxorr

**Comment by Hellsing** [comment]
I remember DZ being part of our project aswell, how comes he changed so much? :^ )

**Comment by blackyy** [comment]
He had too much contact with me, sorry. Keepo

**Comment by DZ191** [comment]
Hellsing I think I'm slightly bipolar..

**Comment by DZ191** [comment]
Plus please, do we wanna forget the infamous 'Asuna says nulled is stupid' thread from like 4 months ago :^ )

**Comment by myo** [comment]
nulled sux atm

**Comment by LoLHTML** [comment]
Hi I am looking for skilled HTML devs for my new project. PM me

**Comment by ChewyMoon** [comment]
Is that ohm XD

**Comment by nabbhacker** [comment]
ohm pls Kappa

**Comment by LoLHTML** [comment]
better api
better community (of course)
will be 100% undetected (as expected)
first 200 alpha tester get an exclusive badge

**Comment by jQueryBase64MyAss** [comment]
:100:

**Comment by Hellsing** [comment]
Ohm pls

**Comment by DZ191** [comment]
:top: kek

**Comment by myo** [comment]
LoLHTML is definitely going to be the next big thing. It's just amazing how powerful this little piece of software can be compared to the currently popular "L#" and the that sounds gay "EloBuddy".

LoLHTML will take over the market on it's release day. You heard it here first.

**Comment by ChewyMoon** [comment]
@LoLHTML please contact me about this new amazing leauge of legends tool! I was wondering if I sign up, will I get a free gay fuck buddy?

**Comment by blackyy** [comment]
@LoLHTML I'm interested in this new project. I could assist you with the HTML Color Codes. :+1: 
Pretty sure that we will be the next big thing if done right. Looking forward to your response.

**Comment by DZ191** [comment]
TIME TO REVIVE THIS!

**Comment by blackyy** [comment]
Freundschaftsnetzwerk™

**Comment by tr33s** [comment]
qq

**Comment by ChewyMoon** [comment]
im fucking bored

**Comment by DZ191** [comment]
hi fucking bored.

**Comment by ChewyMoon** [comment]
go fuck yourself

**Comment by DZ191** [comment]
Rude

**Comment by ChewyMoon** [comment]
:chewy:

**Comment by blackyy** [comment]
:jquery:

**Pull request merged**
